### ISSUE TITLE
Revamp work type mappings to match new vocabulary in ORCID

### ISSUE THREAD

**Issue by gthorisson** [ORCID-EU-Labs/DataCite-ORCID#1]
Need to revisit type mapping logic in `lib/orcid_claim.rb` and expand to match the new work type vocabulary in ORCID which is drawn from the CASRAI dictionary (http://dictionary.casrai.org)

**Comment by lpaglione** [comment]
You can find the release candidate XSD (which includes these new work types) for ORCID here: https://github.com/ORCID/ORCID-Source/blob/master/orcid-model/src/main/resources/orcid-message-1.1.0.xsd

Note that it is a release candidate, so it could evolve before finalized.

**Comment by gthorisson** [comment]
Done, mainly in changeset 337d92777aa7d367ce90a7d49b2e87d0bec14330
