### ISSUE TITLE
Undefined method `solr_url' for Sinatra::Application:Class

### ISSUE THREAD

**Issue by rcpeters** [ORCID-EU-Labs/DataCite-ORCID#3]
When attempting to run vagrant on a local machine:

Error message:
undefined method `solr_url' for Sinatra::Application:Class
Exception class:
NoMethodError
Application root:
/vagrant

![ruby rack application could not be started](https://cloud.githubusercontent.com/assets/192996/2720055/962e973e-c56a-11e3-8155-a6a0fd53d690.png)

**Comment by mfenner** [comment]
I haven't run this application in a while, and Vagrant has also changed. I now use the omnibus vagrant plugin to install Chef and use this box:

http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box

I can run Vagrant with the application in the next few days and make tweaks as necessary.

The specific problem here is that `solr_url` is not set in your `config/settings.yml`. It should be `http://search.datacite.org`.
